<script>
    /*
Show me:
- "Led backend development using Python/Django, building RESTful APIs that handle 100k daily requests"
- "Architected and implemented a React-based dashboard, reducing load times by 60%"
    */
    import Table from "../lib/components/table/Table.svelte";

    const data = [
        {
            rank: 1,
            name: "Detected",
            uri: "https://www.detected.co/",
            location: "London",
            keywords: "kyb",
            technology: "web mobile",
            notes: "CTO - https://www.linkedin.com/in/peter-youell-2863191a/",
        },
        {
            rank: 2,
            name: "CheckedSafe",
            uri: "https://www.checkedsafe.com/",
            location: "Burnley",
            keywords: "vehicle fleet risk",
            technology: "web mobile",
            notes: "nv",
        },
        {
            rank: 3,
            name: "Elliptic",
            uri: "https://www.elliptic.co/contact",
            location: "London, New York, Singapore, Tokyo, UAE",
            keywords: "blockchain, crypto",
            technology: "",
            notes: "",
        },
        {
            rank: 4,
            name: "TAINA Technology",
            uri: "https://www.taina.tech/",
            location: "London, New York, Hong Kong",
            keywords: "tax",
            technology: "react c#",
            notes: "Roger Wood placed Michael Asaad?\https://www.linkedin.com/in/maria-scott-taina/ CEO",
        },
        {
            rank: 5,
            name: "Nivo",
            uri: "https://www.nivohub.com/",
            location: "Manchester",
            keywords: "verified identty messaging",
            technology: "",
            notes: "",
        },
        {
            rank: 6,
            name: "Cleverchain",
            uri: "https://cleverchain.ai/",
            location: "London",
            keywords: "CDD, AI",
            technology: "",
            notes: "CPO Reem el Seed https://www.linkedin.com/in/reemelseed/",
        },
        {
            rank: 7,
            name: "Recordsure",
            uri: "https://recordsure.com/",
            location: "London",
            keywords: "AI speech document recording",
            technology: "",
            notes: "Send your CV to careers@recordsure.com with an overview of what you can bring to the team.",
        },
        {
            rank: 8,
            name: "FundApps",
            uri: "https://www.fundapps.co/",
            location: "London, New York, Singapore",
            keywords: "",
            technology: "",
            notes: "nv",
        },
        {
            rank: 9,
            name: "Algodynamix",
            uri: "https://www.algodynamix.com/",
            location: "London",
            keywords: "risk forcasting",
            technology: "",
            notes: "",
        },
        {
            rank: 10,
            name: "Kalgera",
            uri: "https://www.kalgera.com/",
            location: "London",
            keywords: "protect vulnerable customers",
            technology: "ai",
            notes: "",
        },
        {
            rank: 11,
            name: "Ravelin",
            uri: "https://www.ravelin.com/",
            location: "London",
            keywords: "fraud prevention",
            technology: "",
            notes: "Acquired by WorldPay",
            hide: true,
        },
        {
            rank: 12,
            name: "Onfido",
            uri: "https://onfido.com/",
            location: "London",
            keywords: "Identity verification",
            technology: "",
            notes: "",
        },
        {
            rank: 13,
            name: "ComplyAdvantage",
            uri: "https://complyadvantage.com/",
            location: "London, New York, Lisbon",
            keywords: "AML",
            technology: "",
            notes: "tech in Lisbon?",
        },
        {
            rank: 14,
            name: "Encompass",
            uri: "https://www.encompasscorporation.com/",
            location: "London, New York, Glasgow, Ontario",
            keywords: "KYC, CDD",
            technology: "",
            notes: "Interest #js-careers-jobs-block",
        },
        {
            rank: 15,
            name: "Autorek",
            uri: "https://www.autorek.com/",
            location: "London, New York, Glasgow, Edinborough",
            keywords: "reconciliation",
            technology: "",
            notes: "register",
        },
        {
            rank: 16,
            name: "SmartSearch",
            uri: "https://www.smartsearch.com/",
            location: "Ilkley",
            keywords: "AML checks",
            technology: "",
            notes: "",
        },
        {
            rank: 17,
            name: "Umazi",
            uri: "https://www.umazi.io/",
            location: "London",
            keywords: "odd",
            technology: "blockchain",
            notes: "small",
        },
        {
            rank: 18,
            name: "Worksmart",
            uri: "https://www.worksmart.co.uk/",
            location: "Milton Keynes",
            keywords: "smcr",
            technology: "",
            notes: "nv",
        },
        {
            rank: 19,
            name: "Xapien",
            uri: "https://xapien.com/",
            location: "London",
            keywords: "ODD",
            technology: "python, ai, AWS",
            notes: "",
        },
        {
            rank: 20,
            name: "Konfir",
            uri: "https://www.konfir.com/",
            location: "London",
            keywords: "Employment & Income Verifications",
            technology: "",
            notes: "",
        },
        {
            rank: 21,
            name: "ClearScore",
            uri: "https://www.clearscore.com/",
            location: "London",
            keywords: "Credit score",
            technology: "Java, Kafka",
            notes: "no",
        },
        {
            rank: 22,
            name: "Featurespace",
            uri: "https://www.featurespace.com/",
            location: "Cambridge. Atlanta",
            keywords: "Fraud detection",
            technology: "",
            notes: "",
        },
        {
            rank: 23,
            name: "Novatus",
            uri: "https://novatus.global/",
            location: "London, Sydney",
            keywords: "reporting",
            technology: "",
            notes: "",
        },
        {
            rank: 24,
            name: "SteelEye",
            uri: "https://www.steel-eye.com/",
            location: "London",
            keywords: "Trade & Comms Surveillance",
            technology: "",
            notes: "tech in Porto & India",
        },
        {
            rank: 25,
            name: "TrackMyRisks",
            uri: "https://trackmyrisks.com/",
            location: "Norwich",
            keywords: "Governance, Risk, Compliance",
            technology: "",
            notes: "",
        },
        {
            rank: 26,
            name: "Napier",
            uri: "https://www.napier.ai/",
            location: "London, Delaware, Singapore, Australia, Dubai",
            keywords: "AML",
            technology: "AI",
            notes: "",
        },
        {
            rank: 27,
            name: "Pelican AI",
            uri: "https://www.pelican.ai/",
            location: "London, new Jersey, Hong Kong, India, Dubai",
            keywords: "payments",
            technology: "",
            notes: "",
        },
        {
            rank: 28,
            name: "Quantexa",
            uri: "https://www.quantexa.com/",
            location: "London",
            keywords: "risk, crime, AML",
            technology: "scala",
            notes: "",
        },
        {
            rank: 29,
            name: "iProov",
            uri: "https://www.iproov.com/",
            location: "London",
            keywords: "Onboard and authenticate",
            technology: "flutter",
            notes: "contact us at Careers@iProov.com.",
        },
        {
            rank: 30,
            name: "Qomply",
            uri: "https://qomply.co.uk/",
            location: "London, New York",
            keywords: "reporting",
            technology: "",
            notes: "",
        },
        {
            rank: 31,
            name: "W2 Global Data",
            uri: "https://www.w2globaldata.com/",
            location: "Winnersh",
            keywords: "KYC, AML, Anti-Fraud, and Identity Verification",
            technology: "",
            notes: "",
        },
        {
            rank: 32,
            name: "Ruleguard",
            uri: "https://insights.ruleguard.com/",
            location: "London",
            keywords: "",
            technology: "",
            notes: "",
        },
        {
            rank: 33,
            name: "Suade Labs",
            uri: "https://suade.org/",
            location: "London, New York, Singapore",
            keywords: "",
            technology: "javascript, vue",
            notes: "nv",
        },
        {
            rank: 34,
            name: "CoVi Analytics",
            uri: "https://www.covianalytics.com/",
            location: "London",
            keywords: "policy, risk, process",
            technology: "",
            notes: "",
        },
        {
            rank: 35,
            name: "CUBE",
            uri: "https://cube.global/",
            location: "London, New York",
            keywords: "reg platform, SAAS",
            technology: "",
            notes: "applied for contract 14/02, THEY NEED ME",
        },
        {
            rank: 36,
            name: "Nuggets",
            uri: "https://www.nuggets.life/",
            location: "",
            keywords: "Decentralized identity, payment",
            technology: "",
            notes: "",
        },
        {
            rank: 37,
            name: "AuditComply",
            uri: "https://www.auditcomply.com/",
            location: "Belfast",
            keywords: "QMS",
            technology: "",
            notes: "",
        },
        {
            rank: 38,
            name: "ComplyPortal",
            uri: "https://complyportal.uk/",
            location: "London",
            keywords: "SMCR, Promotions, Risk, training, KYC",
            technology: "",
            notes: "Email: info@complyportal.uk",
        },
        {
            rank: 39,
            name: "Surety",
            uri: "https://www.complianceasaservice.com/surety",
            location: "Hertford",
            keywords: "",
            technology: "",
            notes: "",
            hide: true,
        },
        {
            rank: 40,
            name: "FeedStock",
            uri: "https://www.feedstock.com/",
            location: "London",
            keywords: "",
            technology: "ai",
            notes: "",
        },
        {
            rank: 41,
            name: "Cambridge Intelligence",
            uri: "https://cambridge-intelligence.com/",
            location: "Canbridge",
            keywords: "visualisation",
            technology: "javascript",
            notes: "nv",
        },
        {
            rank: 42,
            name: "Kaizen Reporting",
            uri: "https://www.kaizenreporting.com/",
            location: "London, Amsterdam",
            keywords: "",
            technology: "",
            notes: "",
        },
        {
            rank: 43,
            name: "Autologyx",
            uri: "https://autologyx.com/",
            location: "London",
            keywords: "ops",
            technology: "",
            notes: "nv, cold",
        },
        {
            rank: 44,
            name: "Credit Benchmark",
            uri: "https://www.creditbenchmark.com/",
            location: "New York, London",
            keywords: "credit risk",
            technology: "",
            notes: "",
        },
        {
            rank: 45,
            name: "OpusDatum",
            uri: "https://www.opusdatum.com/",
            location: "London",
            keywords: "financial crime",
            technology: "",
            notes: "",
        },
        {
            rank: 46,
            name: "PassFort",
            uri: "https://www.moodys.com/web/en/us/kyc/products/passfort.html",
            location: "",
            keywords: "",
            technology: "",
            notes: "Moodies",
            hide: true,
        },
        {
            rank: 47,
            name: "Global Screening Services",
            uri: "https://www.gss-rose.com/",
            location: "London",
            keywords: "Sanctions",
            technology: "kafka, aws, mongo, postgres, s3, ec2, docker",
            notes: "",
        },
        {
            rank: 48,
            name: "Armalytix",
            uri: "https://armalytix.com/",
            location: "London, Chester",
            keywords: "AML",
            technology: "",
            notes: "email joinus@armalytix.com",
        },
        {
            rank: 49,
            name: "Proxymity",
            uri: "https://www.proxymity.io/",
            location: "London, Manchester, New York, Tel Aviv, Melbourne",
            keywords: "proxy voting",
            technology: "angular",
            notes: "tech in Manchester",
        },
        {
            rank: 50,
            name: "Rossum",
            uri: "https://rossum.ai/ai-agents/",
            location: "Czech Republic, US, UK, Luxembourg",
            keywords: "document processing",
            technology: "python",
            notes: "dev in Prague",
        },
        {
            rank: 51,
            name: "Trustfull",
            uri: "https://trustfull.com/",
            location: "Milan",
            keywords: "",
            technology: "",
            notes: "",
        },
        {
            rank: 52,
            name: "Shield",
            uri: "https://www.shieldfc.com/",
            location: "London, Lisbon, Singapore",
            keywords: "record management",
            technology: "",
            notes: "java spring",
        },
        {
            rank: 53,
            name: "Signifyd",
            uri: "https://www.signifyd.com/",
            location: "San Francisco, London, Budapest",
            keywords: "",
            technology: "ml",
            notes: "nv",
        },
        {
            rank: 54,
            name: "Access Group",
            uri: "https://www.theaccessgroup.com/",
            location: "Loughborough",
            keywords: "",
            technology: "",
            notes: "tech in romania",
        },
        {
            rank: 55,
            name: "Vanta",
            uri: "https://www.vanta.com/",
            location: "San Francisco, New York, Sydney, London, Dublin",
            keywords: "trust, risk",
            technology: "",
            notes: "applied 14/02",
        },
        {
            rank: 56,
            name: "SureCloud",
            uri: "https://www.surecloud.com/",
            location: "London",
            keywords: "risk management, GRC",
            technology: "",
            notes: "",
        },
    ].filter((r) => !r.hide);

    const config = {
        columns: [
            {
                id: "name",
                type: "string",
                label: "Name",
            },
            {
                id: "uri",
                type: "string",
                label: "Website",
            },
            {
                id: "location",
                type: "string",
                label: "Location",
            },
            {
                id: "keywords",
                type: "string",
                label: "Business Areas",
            },
            {
                id: "technology",
                type: "string",
                label: "Technology",
            },
            {
                id: "notes",
                type: "string",
                label: "Notes",
            },
            {
                id: "rank",
                type: "number",
                label: "Rank",
            },
        ],
        sort: { col: "name", asc: 1 },
        showIndex: true,
    };
</script>

<h1 style="text-align: center;"><strong>The RegTech 50 for 2023</strong></h1>
<Table {data} {config} />
